# action.yml
name: 'iamdevops995-docker-action'
description: 'Greet someone from docker action'
inputs:
  github_token:  # id of input
    description: 'provide github_token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
  branding:
    icon: 'award'
    color: 'green'
